name: TEST
on:
  pull_request:
  push:
    branches:
      - main
      - dev
      - release

jobs:
  flutter_test:
    name: Run flutter test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "17.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
          flutter-version: "2.10.2"
      - run: flutter pub get
      - run: flutter analyze --no-fatal-infos --no-fatal-warnings
      - run: flutter test
